- action: "Run Fastlane for Android"
  type: "FASTLANE_ANDROID"
  trigger_time: "ON_EVERY_EXECUTION"
  shell: "SH"
  build_tool_version: "30.0.3"
  commands: |-
    bundle install
    bundle exec fastlane android deploy
